//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int IdGasto { get; set; }
        public string Concepto { get; set; }
        public string Observacion { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> IdLiga { get; set; }
    
        public virtual Liga Liga { get; set; }
    }
}
